"""Generate GitHub Pages dashboard files from investment records."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, List

RECORDS_PATH = Path("docs/data/investment_records.csv")
DOCS_DIR = Path("docs")
DOCS_DATA_DIR = DOCS_DIR / "data"
SERIES_PATH = DOCS_DATA_DIR / "series.json"
INDEX_PATH = DOCS_DIR / "index.html"


def _to_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _load_rows() -> List[Dict[str, str]]:
    if not RECORDS_PATH.exists():
        return []
    with RECORDS_PATH.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _series(rows: List[Dict[str, str]]) -> Dict[str, object]:
    records = []
    for row in rows:
        records.append(
            {
                "date": row.get("date", ""),
                "status": row.get("status", ""),
                "btc_price": _to_float(row.get("btc_price", "0")),
                "cum_invest_usdt": _to_float(row.get("cum_invest_usdt", "0")),
                "portfolio_value_usdt": _to_float(row.get("portfolio_value_usdt", "0")),
                "pnl_usdt": _to_float(row.get("pnl_usdt", "0")),
                "pnl_ratio": _to_float(row.get("pnl_ratio", "0")),
                "benchmark_value_usdt": _to_float(row.get("benchmark_value_usdt", "0")),
                "benchmark_pnl_usdt": _to_float(row.get("benchmark_pnl_usdt", "0")),
                "benchmark_pnl_ratio": _to_float(row.get("benchmark_pnl_ratio", "0")),
                "alpha_usdt": _to_float(row.get("alpha_usdt", "0")),
                "alpha_ratio": _to_float(row.get("alpha_ratio", "0")),
            }
        )

    summary = {
        "total_records": len(records),
        "latest": records[-1] if records else None,
    }
    return {"summary": summary, "records": records}


def _build_html() -> str:
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>BTC Enhanced DCA Dashboard</title>
  <style>
    :root {
      --bg: #f5f7fb;
      --card: #ffffff;
      --text: #111827;
      --muted: #6b7280;
      --primary: #d97706;
      --accent: #0891b2;
      --line: #e5e7eb;
      --ok: #16a34a;
      --bad: #dc2626;
    }
    body {
      margin: 0;
      font-family: "Segoe UI", "PingFang SC", sans-serif;
      background: linear-gradient(160deg, #eef2ff, var(--bg));
      color: var(--text);
    }
    .wrap {
      max-width: 1100px;
      margin: 0 auto;
      padding: 24px 16px 48px;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 12px;
      margin-bottom: 16px;
    }
    .card {
      background: var(--card);
      border: 1px solid var(--line);
      border-radius: 12px;
      padding: 14px;
      box-shadow: 0 4px 20px rgba(17, 24, 39, 0.06);
    }
    .label { color: var(--muted); font-size: 13px; }
    .value { font-size: 24px; font-weight: 700; margin-top: 8px; }
    .chart-card { margin-top: 12px; }
    .chart-title { margin: 0 0 8px; font-size: 15px; }
    .table-wrap { overflow-x: auto; margin-top: 16px; }
    table { width: 100%; border-collapse: collapse; background: var(--card); }
    th, td { border: 1px solid var(--line); padding: 8px; font-size: 13px; }
    th { background: #f8fafc; text-align: left; }
    .footer { color: var(--muted); font-size: 12px; margin-top: 12px; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>BTC Enhanced DCA Performance</h1>
    <div class="grid" id="summary"></div>

    <div class="card chart-card">
      <h2 class="chart-title">Portfolio Value vs Benchmark</h2>
      <canvas id="valueChart" height="110"></canvas>
    </div>

    <div class="card chart-card">
      <h2 class="chart-title">PnL Ratio vs Benchmark</h2>
      <canvas id="ratioChart" height="110"></canvas>
    </div>

    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Status</th>
            <th>BTC Price</th>
            <th>Cumulative Invest</th>
            <th>Portfolio Value</th>
            <th>PnL Ratio</th>
            <th>Benchmark PnL Ratio</th>
          </tr>
        </thead>
        <tbody id="rows"></tbody>
      </table>
    </div>

    <div class="footer">Auto-generated by GitHub Actions.</div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
  <script>
    const usd = (v) => Number(v || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
    const pct = (v) => `${(Number(v || 0) * 100).toFixed(2)}%`;

    fetch("./data/series.json")
      .then((res) => res.json())
      .then((data) => {
        const records = data.records || [];
        const latest = data.summary?.latest;
        const summaryNode = document.getElementById("summary");
        const rowsNode = document.getElementById("rows");

        if (!latest) {
          summaryNode.innerHTML = "<div class='card'><div class='label'>Status</div><div class='value'>No data yet</div></div>";
          return;
        }

        const cards = [
          ["Records", data.summary.total_records],
          ["Cumulative Invest (USDT)", usd(latest.cum_invest_usdt)],
          ["Portfolio Value (USDT)", usd(latest.portfolio_value_usdt)],
          ["PnL (USDT)", usd(latest.pnl_usdt)],
          ["PnL Ratio", pct(latest.pnl_ratio)],
          ["Benchmark PnL Ratio", pct(latest.benchmark_pnl_ratio)],
          ["Alpha Ratio", pct(latest.alpha_ratio)]
        ];
        summaryNode.innerHTML = cards.map(([k, v]) =>
          `<div class="card"><div class="label">${k}</div><div class="value">${v}</div></div>`
        ).join("");

        rowsNode.innerHTML = records.slice().reverse().slice(0, 30).map((row) => `
          <tr>
            <td>${row.date}</td>
            <td>${row.status}</td>
            <td>${usd(row.btc_price)}</td>
            <td>${usd(row.cum_invest_usdt)}</td>
            <td>${usd(row.portfolio_value_usdt)}</td>
            <td>${pct(row.pnl_ratio)}</td>
            <td>${pct(row.benchmark_pnl_ratio)}</td>
          </tr>
        `).join("");

        const labels = records.map((x) => x.date);
        const valueCtx = document.getElementById("valueChart");
        new Chart(valueCtx, {
          type: "line",
          data: {
            labels,
            datasets: [
              { label: "Strategy Value", data: records.map((x) => x.portfolio_value_usdt), borderColor: "#d97706", tension: 0.25 },
              { label: "Benchmark Value", data: records.map((x) => x.benchmark_value_usdt), borderColor: "#0891b2", tension: 0.25 },
              { label: "Cumulative Invest", data: records.map((x) => x.cum_invest_usdt), borderColor: "#6b7280", tension: 0.25 }
            ]
          },
          options: { responsive: true, maintainAspectRatio: true }
        });

        const ratioCtx = document.getElementById("ratioChart");
        new Chart(ratioCtx, {
          type: "line",
          data: {
            labels,
            datasets: [
              { label: "Strategy PnL Ratio", data: records.map((x) => x.pnl_ratio), borderColor: "#16a34a", tension: 0.25 },
              { label: "Benchmark PnL Ratio", data: records.map((x) => x.benchmark_pnl_ratio), borderColor: "#dc2626", tension: 0.25 },
              { label: "Alpha Ratio", data: records.map((x) => x.alpha_ratio), borderColor: "#111827", tension: 0.25 }
            ]
          },
          options: {
            responsive: true,
            maintainAspectRatio: true,
            scales: { y: { ticks: { callback: (value) => `${(value * 100).toFixed(1)}%` } } }
          }
        });
      })
      .catch((err) => {
        document.getElementById("summary").innerHTML =
          `<div class='card'><div class='label'>Error</div><div class='value'>${err}</div></div>`;
      });
  </script>
</body>
</html>
"""


def generate_dashboard() -> int:
    rows = _load_rows()
    series = _series(rows)

    DOCS_DATA_DIR.mkdir(parents=True, exist_ok=True)
    SERIES_PATH.write_text(json.dumps(series, ensure_ascii=False, indent=2), encoding="utf-8")
    INDEX_PATH.write_text(_build_html(), encoding="utf-8")
    print(f"[INFO] Generated dashboard files under {DOCS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(generate_dashboard())

